routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();
Route::group(['middleware'=>['auth']],function(){
	Route::get('/', function () {
    	return view('home');
	});
	Route::resource('vendors','VendorsController');
	Route::resource('inventories', 'InventoriesController');
	Route::resource('sells', 'SellsController');
	Route::resource('categories', 'CategoryController');
	Route::resource('products', 'ProductController');
});




Route::get('/home', 'HomeController@index')->name('home');

app/Models/Inventory.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Inventory extends Model
{
   protected $table = 'inventories';
   protected $guarded = ['id'];

   public function vendor(){
   		return $this->belongsTo(Vendor::class,'vendor_id');
   }
   public function users()
   {
   		return $this->belongsTo(User::class,'user_id');
   }
}

app/Http/Controllers/InventoriesController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use App\Models\Inventory;
use App\Models\Vendor;
use Illuminate\Support\Facades\Storage;

class InventoriesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $inven = Inventory::with('vendor')->get();
      //  dd($inven);
        return view('inventory.index',compact('inven'));
        
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $vendors = Vendor::pluck('company_name','id');
        $vendors->prepend('--Select a vendor--','');
        // return $vendors;
        return view('inventory.create',compact('vendors'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $rules = [
            "vendor_id"     => 'required',
            "product_name"  => 'required',
            "purchase_date" => 'required',
            "product_des"   => 'required',
            "price"         => 'required',
            'image'=>'required'
        ];
        // return $request->all();
        $this->validate($request, $rules);
        DB::beginTransaction();
        try {
            $data = $request->all();
            //$data['user_id']=auth()->user()->id;
            $image = $request->file('image');
            $file_name = $data['product_name'].".".$image->getClientOriginalExtension();
            // Storage::disk('public')->put('/',$image);
            $image->move(storage_path('app/public'),$file_name);
            $data['image_path'] = $file_name;
            unset($data['image']);
            Inventory::create($data);
            DB::commit();
        } catch (\Exception $e) {
            DB::rollback();
            return redirect()->route('inventories.index')->with('error_message', $e->getMessage());
        }
        return redirect()->route('inventories.index')->with('success_message', "Inventory created successfully");
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/inventory/create.blade.php
@extends('layouts.app')
@section('content')
<div class="container-fluid">
	{!! Form::open(['route'=>'inventories.store','files' => true])!!}
	<div class="card" style="overflow: hidden">
		<div class="card-header">
			<strong>Inventory Entry</strong>
			<small>Form</small>
		</div>
		<div class="card-body card-block">
			<div class="form-group">
				{!! Form::label('product_name','Product Name:',['class'=>'form-control-label']) !!}
				<!-- <label for="company" class=" form-control-label">Company Name</label> -->
				{!! Form::text("product_name",null,['placeholder'=>'Enter your product name','class'=>"form-control"])!!}
				<!-- <input type="text" id="company" placeholder="Enter your company name" class="form-control"> -->
				{!! $errors->first('product_name','<p class="text text-danger">:message</p>') !!}
			</div>
			<div class="form-group">
				{!! Form::label('vendor_id','Vendor Name:',['class'=>'form-control-label']) !!}
				<!-- <label for="company" class=" form-control-label">Company Name</label> -->
				{!! Form::select("vendor_id",$vendors,null,['class'=>"form-control"])!!}
				<!-- <input type="text" id="company" placeholder="Enter your company name" class="form-control"> -->
				{!! $errors->first('vendor_id','<p class="text text-danger">:message</p>') !!}
			</div>
			<div class="form-group">
				{!! Form::label('purchase_date', 'Purchase date', ['class'=>'form-control-label']) !!}
				<!-- <label for="ceo_name" class=" form-control-label">CEO Name</label> -->
				{!! Form::date('purchase_date', null, ['class'=>'form-control']) !!}
				<!-- <input type="text" id="vat" placeholder="Enter your CEO name" class="form-control"> -->
				{!! $errors->first('purchase_date', '<p class="text text-danger">:message</p>') !!}
			</div>
			<div class="form-group">
				{!! Form::label('price_per_product', 'Price per product', ['class'=>'form-control-label']) !!}
				<!-- <label for="ceo_name" class=" form-control-label">CEO Name</label> -->
				{!! Form::number('price_per_product', null, ['placeholder'=>'Enter the price', 'class'=>'form-control']) !!}
				<!-- <input type="text" id="vat" placeholder="Enter your CEO name" class="form-control"> -->
				{!! $errors->first('price_per_product', '<p class="text text-danger">:message</p>') !!}
			</div>
			<div class="row form-group">
				<div class="col-8">
					<div class="form-group">
						{!! Form::label('quantity', 'Quantity:', ['class'=>'form-control-label']) !!}
						<!-- <label for="postal-code" class=" form-control-label">Mobile NO: </label> -->
						{!! Form::number('quantity', null, ['placeholder'=>'Enter amount', 'class'=>'form-control']) !!}
						<!-- <input type="text" id="postal-code" placeholder="Enter your mobile number" class="form-control"> -->
						{!! $errors->first('quantity', '<p class="text text-danger">:message</p>') !!}
					</div>
				</div>
				<div class="col-8">
					<div class="form-group">
						{!! Form::label('total_amount', 'Total Amount', ['class'=>'form-control-label']) !!}
						<!-- <label for="city" class=" form-control-label">Contact Person</label> -->
						{!! Form::number('total_amount', null, ['placeholder'=>'Enter price', 'class'=>'form-control']) !!}
						<!-- <input type="text" id="city" placeholder="Enter contact person name" class="form-control"> -->
						{!! $errors->first('total_amount', '<p class="text text-danger">:message</p>') !!}
					</div>
				</div>
				<div class="col-8">
					{!!Form::file('image')!!}
				</div>
			</div>
		</div>
		<div class="card-footer">
			<button type="submit" class="btn btn-primary btn-lg pull-right">
				<i class="fa fa-dot-circle-o"></i> Submit
			</button>
		</div>
	</div>
	{!! Form::close() !!}
</div>
@endsection

resources/views/inventory/index.blade.php
@extends('layouts.app')
@section('content')
    <div class="container-fluid">
        @if(Session::has('success_message'))
            <div class="alert alert-success alert-dismissible">
              <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
              {{Session::get('success_message')}}
            </div>
        @endif
        @if(Session::has('error_message'))
            <div class="alert alert-success alert-dismissible">
              <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
              {{Session::get('error_message')}}
            </div>
        @endif
        <a class="btn btn-primary pull-right" style="margin-bottom: 10px;" href="{{URL::route('inventories.create')}}">
            ADD NEW
            <i class="fas fa-plus-circle"></i>
        </a>
        <div class="table-responsive m-b-40">

            <table class="table table-borderless table-data3">
                <thead>
                    <tr>
                        <th>SL. No</th>
                        <th>Product Name</th>
                        <th>Product Description</th>
                        <th>Price</th>
                        <th>Vendor</th>
                        <th>User ID</th>
                        <th>Images</th>
                        <th>Quantity</th>
                    </tr>
                </thead>
                <tbody>
                    @php($i=1)
                    @forelse($inven as $inventory)
                       
                        <tr>
                            <td>{{$i++}}</td>
                            <td>{{$inventory->product_name}}</td>
                            <td>{{$inventory->product_des}}</td>
                            <td>{{$inventory->price}}</td>
                            <td>{{$inventory->vendor->company_name}}</td>
                            <td>{{$inventory->users->name}}</td>
                            <td><img style="width: 100px;" class="img-responsive" src="{{asset('storage/'.$inventory->image_path)}}"></td>
                            <td>{{$inventory->quantity}}</td>
                        </tr>
                      

                    @empty
                    <tr>
                        <td colspan="8" class="bg-warning">No Data available</td>
                    </tr>
                    @endforelse
                </tbody>
            </table>
        </div>
    </div>
@endsection()