routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();
Route::group(['middleware'=>['auth']],function(){
	Route::get('/', function () {
    	return view('home');
	});
	Route::resource('vendors','VendorsController');
	Route::resource('inventories', 'InventoriesController');
	Route::resource('sells', 'SellsController');
	Route::resource('categories', 'CategoryController');
	Route::resource('products', 'ProductController');
});




Route::get('/home', 'HomeController@index')->name('home');

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    protected $table = 'categories';
    protected $guarded = ['id'];
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Models\Category;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories = Category::all();
        //dd($categories);
        return view('category.index',compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('category.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //dd($request->all());
        DB::beginTransaction();
        try{
            /*Category::insert($request->except('_token'));*/
            Category::create($request->all());
            DB::commit();
            //dd('ok');
        }catch (\Exception $e){
            DB::rollBack();
            //dd('not ok');
            return redirect()->route('categories.index')->with('error_message',$e->getMessage());
        }

        //dd('ok');
        return redirect()->route('categories.index')->with('success_message', "Category created successfully");
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/category/create.blade.php
@extends('layouts.app')
@section('content')
    <div class="container-fluid">
        {!! Form::open(['route'=>'categories.store'])!!}
        <div class="card" style="overflow: hidden">
            <div class="card-header">
                <strong>Ctegory Entry</strong>
                <small>Form</small>
            </div>
            <div class="card-body card-block">
                <div class="form-group">
                {!! Form::label('category_name','Category',['class'=>'form-control-label']) !!}
                {!! Form::text("category_name",null,['placeholder'=>'Enter your category name','class'=>"form-control"])!!}
                {{--{!! $errors->first('company_name','<p class="text text-danger">:message</p>') !!}--}}
                </div>
                <div class="form-group">
                {!! Form::label('category_description','Category Description',['class'=>'form-control-label']) !!}
                {!! Form::text("category_description",null,['placeholder'=>'Enter your category description','class'=>"form-control"])!!}
                {{--{!! $errors->first('company_name','<p class="text text-danger">:message</p>') !!}--}}
                </div>

            </div>
            <div class="card-footer">
                <button type="submit" class="btn btn-primary btn-lg pull-right">
                    <i class="fa fa-dot-circle-o"></i> Submit
                </button>
            </div>
        </div>
        {!! Form::close() !!}
    </div>
@endsection

resources/views/category/index.blade.php
@extends('layouts.app')
@section('content')
    <div class="container-fluid">
        @if(Session::has('success_message'))
            <div class="alert alert-success alert-dismissible">
                <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                {{Session::get('success_message')}}
            </div>
        @endif
        @if(Session::has('error_message'))
            <div class="alert alert-success alert-dismissible">
                <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                {{Session::get('error_message')}}
            </div>
        @endif
        <a class="btn btn-primary pull-right" style="margin-bottom: 10px;" href="{{URL::route('categories.create')}}">
            ADD NEW
            <i class="fas fa-plus-circle"></i>
        </a>
        <div class="table-responsive m-b-40">

            <table class="table table-borderless table-data3">
                <thead>
                <tr>
                    <th>SL. No</th>
                    <th>Category Name</th>
                    <th>Category Description</th>
                </tr>
                </thead>
                <tbody>
                @php($i=1)
                @forelse($categories as $category)
                    <tr>
                        <td>{{$i++}}</td>
                        <td>{{$category->category_name}}</td>
                        <td>{{$category->category_description}}</td>
                       {{-- <td style="display: flex;;justify-content:space-around;flex-wrap: nowrap;">
                            <a class="btn btn-primary btn-sm" style="margin-right: 2px" href="{{URL::route('vendors.edit',$vendor->id)}}">
                                <i class="fa fa-edit"></i>
                            </a>
                            <a class="btn btn-info btn-sm" href="{{URL::route('vendors.show',$vendor->id)}}">
                                <i class="fa fa-eye"></i>
                            </a>
                        </td>--}}
                    </tr>
                @empty
                    <tr>
                        <td colspan="6" class="bg-warning">No Data available</td>
                    </tr>
                @endforelse
                </tbody>
            </table>
        </div>
    </div>
@endsection()